apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sae-visualizer.fullname" . }}
  labels:
    {{- include "sae-visualizer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "sae-visualizer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sae-visualizer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPRING_REDIS_HOST
              value: {{ .Values.config.valkey.host }}
            - name: SPRING_REDIS_PORT
              value: {{ .Values.config.valkey.port }}
            - name: SPRING_REDIS_STREAMIDS
              value: {{ join ", " .Values.config.valkey.stream_ids }}
            {{- if .Values.auth.enabled }}
            - name: SPRING_PROFILES_ACTIVE
              value: auth
            - name: OIDC-CLIENT-REGISTRATION_AUTHORIZATION-URI
              value: {{ .Values.auth.keycloakRealmUrlExternal }}/protocol/openid-connect/auth
            - name: OIDC-CLIENT-REGISTRATION_TOKEN-URI
              value: {{ .Values.auth.keycloakRealmUrlInternal }}/protocol/openid-connect/token
            - name: OIDC-CLIENT-REGISTRATION_USER-INFO-URI
              value: {{ .Values.auth.keycloakRealmUrlInternal }}/protocol/openid-connect/userinfo
            - name: OIDC-CLIENT-REGISTRATION_JWK-SET-URI
              value: {{ .Values.auth.keycloakRealmUrlInternal }}/protocol/openid-connect/certs
            - name: OIDC-CLIENT-REGISTRATION_END-SESSION-ENDPOINT
              value: {{ .Values.auth.keycloakRealmUrlExternal }}/protocol/openid-connect/logout
            - name: OIDC-CLIENT-REGISTRATION_USERNAMEATTRIBUTE
              value: preferred_username
            - name: OIDC-CLIENT-REGISTRATION_SCOPE
              value: openid
            - name: OIDC-CLIENT-REGISTRATION_REDIRECT-URI
              value: "{baseUrl}/login/oauth2/code/{registrationId}"
            - name: OIDC-CLIENT-REGISTRATION_CLIENT-ID
              value: {{ .Values.auth.clientId }}
            - name: OIDC-CLIENT-REGISTRATION_CLIENT-SECRET
              value: {{ .Values.auth.clientSecret }}
            {{- else }}
            - name: SPRING_PROFILES_ACTIVE
              value: default
            {{- end }}                          
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
