replicaCount: 1

image:
  repository: starwitorg/sae-visualizer
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ${project.version}

nameOverride: ""
fullnameOverride: "sae-visualizer"

config:
  valkey:
    stream_ids: 
      - streamId1
      - streamId2
    host: valkey-primary
    port: 6379

app:
  context_path: "/"

service:
  port: 8080

auth:
  enabled: true
  keycloakRealmUrlInternal: http://internal-hostname/realms/myrealm
  keycloakRealmUrlExternal: https://external-hostname/realms/myrealm
  clientId: clientId
  clientSecret: clientId

ingress:
  enabled: true
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: saevisualizer.cluster.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: saevisualizer.cluster.local
      hosts:
        - saevisualizer.cluster.local
